# Generated by Django 5.1 on 2025-03-09 10:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_categories_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
