# Generated by Django 5.1 on 2025-02-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateonboarding',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='corporateonboarding',
            name='phone_number',
            field=models.CharField(default='+25412345678', max_length=17),
        ),
    ]
