# Generated by Django 5.1 on 2025-02-10 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_corporateonboarding_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateonboarding',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplierengagement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='corporateonboarding',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='corporateonboarding',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
