# Generated by Django 5.1 on 2025-02-25 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_corporateonboarding_date_customerfeedback_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsappNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
