# Generated by Django 5.1 on 2025-02-25 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_whatsappnumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappnumbers',
            name='number',
        ),
        migrations.AddField(
            model_name='whatsappnumbers',
            name='phone_number',
            field=models.CharField(default='0712345678', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +254XXXXXXXXX or 07XXXXXXXX.', regex='^\\+?254\\d{9}$|^07\\d{8}$')]),
        ),
    ]
